### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dozono** [ci010/VoxeLauncher#20]
We need exit button!
We need to setup java path on every startup!

**Comment by ci010** [comment]
Fixed by commit [0c1f58ef773edb1fe58178cf27f6858aa20fe359](https://github.com/ci010/VoxeLauncher/pull/23/commits/0c1f58ef773edb1fe58178cf27f6858aa20fe359) & [1001f4ffb1440c527163e1bfa2cdb6a05941b396](https://github.com/ci010/VoxeLauncher/pull/23/commits/1001f4ffb1440c527163e1bfa2cdb6a05941b396)
